### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by kungknut** [Frozenlock/wacnet#11]
Hi!

I really appreciate this software. However, I don't seem to find a way to handle notifications like alarms, trendlogs etc.

Am I missing something?

Thanks!

**Comment by Frozenlock** [comment]
No, those are not available via the web interface (yet).

**Comment by kungknut** [comment]
Are they available via API or some other way?

**Comment by Frozenlock** [comment]
You might be able to hack your way with the REPL tab.
(Using clojure interop to use the BACnet4J library methods.)

But it pretty much requires you to knowing both Clojure and Java, plus the library in question.

If you want to give it a try, there's a little draft for getting the trendlogs there : https://github.com/Frozenlock/bacure/blob/master/src/bacure/read_properties.clj#L442-L474

I'm pretty busy right now, but I might be able to bump this in the next few weeks if you're willing to finance the development of these features.

Cheers!
