### ISSUE TITLE
Start Wacnet on a different port

### ISSUE THREAD

**Issue by nadamson87** [Frozenlock/wacnet#15]
Is there a way to launch Wacnet using different ports than 47800 and 47808? 
I have an app already running BACnet and I want to have Wacnet use 47809 which is not in use.

**Comment by Frozenlock** [comment]
You can change the BACnet port via the `configs` tab:
![image](https://github.com/user-attachments/assets/64e55c00-c458-4402-81b5-5c592754e20a)

You can also change it manually via a `configs.clj` file in the same working directory as the jar.
To specify the port, it should contain (at minimum) the following:
```clj
{:port 47809}
```


47800 is the port used by the webserver and is currently hardcorded; it cannot be changed.



Also, keep in mind that if you change the default BACnet port, you might not be able to communicate with the BACnet devices using 47808.

**Comment by nadamson87** [comment]
Thanks @Frozenlock !
