### ISSUE TITLE
Unable to start he application

### ISSUE THREAD

**Issue by ram1505** [Frozenlock/wacnet#2]
I'm getting error stating
_Error_: The BACnet port (47808) is already bound to another software. Please close the other software and try again.

I've my company BACnet running on port 47808. How can I launch Wacnet on a different port?

**Comment by Frozenlock** [comment]
The error message is already telling you what you should do.
(Close the other software and try again.)

There is an alternate way to change the BACnet port, but it won't be very helpful; your BACnet network is most probably on the port 47808.

In the same directory as Wacnet, create a file named `configs.clj`.

In it, paste the following and change the port if needed:

``` clj
{:port 47809}
```

Save and restart Wacnet.

As I said, this probably won't help you very much; your BACnet network seems to be on port 47808.
