### ISSUE TITLE
Some devices return this kind of errors

### ISSUE THREAD

**Issue by senamaud** [Frozenlock/wacnet#3]
Where this error come from?
I have some devices returning that kind of errors

**http://localhost:47800/api/v1/bacnet/devices/10/objects/25**

`{
  "status": 500,
  "message": "Internal Server Error",
  "id": "f21693fa-1841-4ee3-8d26-68b52c37d288",
  "error": {
    "error": "clojure.lang.ExceptionInfo: Error on GET {:response #yada.context.Response{:headers {}, :vary #{:media-type}, :produces {:media-type #yada.media_type.MediaTypeMap{:name \"application/json\", :type \"application\", :subtype \"json\", :parameters {}, :quality 1.0}, :charset #yada.charset.CharsetMap{:alias \"UTF-8\", :quality 1.0}}}, :resource yada.resource.Resource, :error #error {\n :cause nil\n :via\n [{:type java.lang.NullPointerException\n   :message nil\n   :at nil}]\n :trace\n []}}",
    "data": "{:response #yada.context.Response{:headers {}, :vary #{:media-type}, :produces {:media-type #yada.media_type.MediaTypeMap{:name \"application/json\", :type \"application\", :subtype \"json\", :parameters {}, :quality 1.0}, :charset #yada.charset.CharsetMap{:alias \"UTF-8\", :quality 1.0}}}, :resource yada.resource.Resource, :error #error {\n :cause nil\n :via\n [{:type java.lang.NullPointerException\n   :message nil\n   :at nil}]\n :trace\n []}}"
  }
}`

**http://localhost:47800/api/v1/bacnet/devices/10/objects?properties=present-value&properties=description**

`{
  "status": 500,
  "message": "Internal Server Error",
  "id": "492df806-9e4c-44b9-9114-6ffcf3786dbc",
  "error": {
    "error": "clojure.lang.ExceptionInfo: Error on GET {:response #yada.context.Response{:headers {}, :vary #{:media-type}, :produces {:media-type #yada.media_type.MediaTypeMap{:name \"application/json\", :type \"application\", :subtype \"json\", :parameters {}, :quality 1.0}, :charset #yada.charset.CharsetMap{:alias \"UTF-8\", :quality 1.0}}}, :resource yada.resource.Resource, :error #error {\n :cause \"nth not supported on this type: PersistentArrayMap\"\n :via\n [{:type java.lang.UnsupportedOperationException\n   :message \"nth not supported on this type: PersistentArrayMap\"\n   :at [clojure.lang.RT nthFrom \"RT.java\" 947]}]\n :trace\n [[clojure.lang.RT nthFrom \"RT.java\" 947]\n  [clojure.lang.RT nth \"RT.java\" 897]\n  [bacure.coerce.type.primitive$c_object_identifier invokeStatic \"primitive.clj\" 96]\n  [bacure.coerce.type.primitive$c_object_identifier invoke \"primitive.clj\" 96]\n  [bacure.coerce.type.primitive$fn__21583 invokeStatic \"primitive.clj\" 107]\n  [bacure.coerce.type.primitive$fn__21583 invoke \"primitive.clj\" 104]\n  [clojure.lang.MultiFn invoke \"MultiFn.java\" 233]\n  [bacure.read_properties$read_property_request invokeStatic \"read_properties.clj\" 102]\n  [bacure.read_properties$read_property_request invoke \"read_properties.clj\" 94]\n  [bacure.read_properties$read_single_property invokeStatic \"read_properties.clj\" 109]\n  [bacure.read_properties$read_single_property invoke \"read_properties.clj\" 106]\n  [bacure.read_properties$read_single_property_with_fallback invokeStatic \"read_properties.clj\" 149]\n  [bacure.read_properties$read_single_property_with_fallback invoke \"read_properties.clj\" 143]\n  [bacure.read_properties$read_individually$iter__22073__22077$fn__22078 invoke \"read_properties.clj\" 181]\n  [clojure.lang.LazySeq sval \"LazySeq.java\" 40]\n  [clojure.lang.LazySeq seq \"LazySeq.java\" 49]\n  [clojure.lang.RT seq \"RT.java\" 521]\n  [clojure.core$seq__4357 invokeStatic \"core.clj\" 137]\n  [clojure.core.protocols$seq_reduce invokeStatic \"protocols.clj\" 24]\n  [clojure.core.protocols$fn__6738 invokeStatic \"protocols.clj\" 75]\n  [clojure.core.protocols$fn__6738 invoke \"protocols.clj\" 75]\n  [clojure.core.protocols$fn__6684$G__6679__6697 invoke \"protocols.clj\" 13]\n  [clojure.core$reduce invokeStatic \"core.clj\" 6545]\n  [clojure.core$group_by invokeStatic \"core.clj\" 6860]\n  [clojure.core$group_by invoke \"core.clj\" 6860]\n  [bacure.read_properties$read_individually invokeStatic \"read_properties.clj\" 187]\n  [bacure.read_properties$read_individually invoke \"read_properties.clj\" 167]\n  [bacure.read_properties$read_properties invokeStatic \"read_properties.clj\" 451]\n  [bacure.read_properties$read_properties invoke \"read_properties.clj\" 425]\n  [clojure.core$partial$fn__4761 invoke \"core.clj\" 2522]\n  [clojure.lang.AFn applyToHelper \"AFn.java\" 154]\n  [clojure.lang.RestFn applyTo \"RestFn.java\" 132]\n  [clojure.core$apply invokeStatic \"core.clj\" 646]\n  [clojure.core$apply invoke \"core.clj\" 641]\n  [bacure.read_properties$read_properties_multiple_objects invokeStatic \"read_properties.clj\" 461]\n  [bacure.read_properties$read_properties_multiple_objects invoke \"read_properties.clj\" 453]\n  [bacure.core$remote_object_properties_with_error invokeStatic \"core.clj\" 79]\n  [bacure.core$remote_object_properties_with_error invoke \"core.clj\" 65]\n  [bacure.core$remote_object_properties invokeStatic \"core.clj\" 95]\n  [bacure.core$remote_object_properties invoke \"core.clj\" 82]\n  [wacnet.api.bacnet.devices$object_list$get_prop_fn__22608 invoke \"devices.clj\" 168]\n  [wacnet.api.bacnet.devices$object_list invokeStatic \"devices.clj\" 174]\n  [wacnet.api.bacnet.devices$object_list invoke \"devices.clj\" 159]\n  [wacnet.api.bacnet.devices$fn__22675 invokeStatic \"devices.clj\" 282]\n  [wacnet.api.bacnet.devices$fn__22675 invoke \"devices.clj\" 278]\n  [yada.methods$apply_response_fn invokeStatic \"methods.clj\" 37]\n  [yada.methods$apply_response_fn invoke \"methods.clj\" 35]\n  [yada.methods$fn__18507$fn__18512 invoke \"methods.clj\" 188]\n  [manifold.deferred$fn__2050$chain___2071 invoke \"deferred.clj\" 860]\n  [clojure.lang.AFn applyToHelper \"AFn.java\" 165]\n  [clojure.lang.RestFn applyTo \"RestFn.java\" 132]\n  [clojure.core$apply invokeStatic \"core.clj\" 650]\n  [clojure.core$apply invoke \"core.clj\" 641]\n  [manifold.deferred$fn__2050$chain___2071$fn__2073 invoke \"deferred.clj\" 889]\n  [manifold.deferred.Listener onSuccess \"deferred.clj\" 219]\n  [manifold.deferred.Deferred$fn__1859 invoke \"deferred.clj\" 379]\n  [clojure.lang.AFn run \"AFn.java\" 22]\n  [io.aleph.dirigiste.Executor$Worker$1 run \"Executor.java\" 62]\n  [manifold.executor$thread_factory$reify__1384$f__1385 invoke \"executor.clj\" 36]\n  [clojure.lang.AFn run \"AFn.java\" 22]\n  [java.lang.Thread run nil -1]]}}",
    "data": "{:response #yada.context.Response{:headers {}, :vary #{:media-type}, :produces {:media-type #yada.media_type.MediaTypeMap{:name \"application/json\", :type \"application\", :subtype \"json\", :parameters {}, :quality 1.0}, :charset #yada.charset.CharsetMap{:alias \"UTF-8\", :quality 1.0}}}, :resource yada.resource.Resource, :error #error {\n :cause \"nth not supported on this type: PersistentArrayMap\"\n :via\n [{:type java.lang.UnsupportedOperationException\n   :message \"nth not supported on this type: PersistentArrayMap\"\n   :at [clojure.lang.RT nthFrom \"RT.java\" 947]}]\n :trace\n [[clojure.lang.RT nthFrom \"RT.java\" 947]\n  [clojure.lang.RT nth \"RT.java\" 897]\n  [bacure.coerce.type.primitive$c_object_identifier invokeStatic \"primitive.clj\" 96]\n  [bacure.coerce.type.primitive$c_object_identifier invoke \"primitive.clj\" 96]\n  [bacure.coerce.type.primitive$fn__21583 invokeStatic \"primitive.clj\" 107]\n  [bacure.coerce.type.primitive$fn__21583 invoke \"primitive.clj\" 104]\n  [clojure.lang.MultiFn invoke \"MultiFn.java\" 233]\n  [bacure.read_properties$read_property_request invokeStatic \"read_properties.clj\" 102]\n  [bacure.read_properties$read_property_request invoke \"read_properties.clj\" 94]\n  [bacure.read_properties$read_single_property invokeStatic \"read_properties.clj\" 109]\n  [bacure.read_properties$read_single_property invoke \"read_properties.clj\" 106]\n  [bacure.read_properties$read_single_property_with_fallback invokeStatic \"read_properties.clj\" 149]\n  [bacure.read_properties$read_single_property_with_fallback invoke \"read_properties.clj\" 143]\n  [bacure.read_properties$read_individually$iter__22073__22077$fn__22078 invoke \"read_properties.clj\" 181]\n  [clojure.lang.LazySeq sval \"LazySeq.java\" 40]\n  [clojure.lang.LazySeq seq \"LazySeq.java\" 49]\n  [clojure.lang.RT seq \"RT.java\" 521]\n  [clojure.core$seq__4357 invokeStatic \"core.clj\" 137]\n  [clojure.core.protocols$seq_reduce invokeStatic \"protocols.clj\" 24]\n  [clojure.core.protocols$fn__6738 invokeStatic \"protocols.clj\" 75]\n  [clojure.core.protocols$fn__6738 invoke \"protocols.clj\" 75]\n  [clojure.core.protocols$fn__6684$G__6679__6697 invoke \"protocols.clj\" 13]\n  [clojure.core$reduce invokeStatic \"core.clj\" 6545]\n  [clojure.core$group_by invokeStatic \"core.clj\" 6860]\n  [clojure.core$group_by invoke \"core.clj\" 6860]\n  [bacure.read_properties$read_individually invokeStatic \"read_properties.clj\" 187]\n  [bacure.read_properties$read_individually invoke \"read_properties.clj\" 167]\n  [bacure.read_properties$read_properties invokeStatic \"read_properties.clj\" 451]\n  [bacure.read_properties$read_properties invoke \"read_properties.clj\" 425]\n  [clojure.core$partial$fn__4761 invoke \"core.clj\" 2522]\n  [clojure.lang.AFn applyToHelper \"AFn.java\" 154]\n  [clojure.lang.RestFn applyTo \"RestFn.java\" 132]\n  [clojure.core$apply invokeStatic \"core.clj\" 646]\n  [clojure.core$apply invoke \"core.clj\" 641]\n  [bacure.read_properties$read_properties_multiple_objects invokeStatic \"read_properties.clj\" 461]\n  [bacure.read_properties$read_properties_multiple_objects invoke \"read_properties.clj\" 453]\n  [bacure.core$remote_object_properties_with_error invokeStatic \"core.clj\" 79]\n  [bacure.core$remote_object_properties_with_error invoke \"core.clj\" 65]\n  [bacure.core$remote_object_properties invokeStatic \"core.clj\" 95]\n  [bacure.core$remote_object_properties invoke \"core.clj\" 82]\n  [wacnet.api.bacnet.devices$object_list$get_prop_fn__22608 invoke \"devices.clj\" 168]\n  [wacnet.api.bacnet.devices$object_list invokeStatic \"devices.clj\" 174]\n  [wacnet.api.bacnet.devices$object_list invoke \"devices.clj\" 159]\n  [wacnet.api.bacnet.devices$fn__22675 invokeStatic \"devices.clj\" 282]\n  [wacnet.api.bacnet.devices$fn__22675 invoke \"devices.clj\" 278]\n  [yada.methods$apply_response_fn invokeStatic \"methods.clj\" 37]\n  [yada.methods$apply_response_fn invoke \"methods.clj\" 35]\n  [yada.methods$fn__18507$fn__18512 invoke \"methods.clj\" 188]\n  [manifold.deferred$fn__2050$chain___2071 invoke \"deferred.clj\" 860]\n  [clojure.lang.AFn applyToHelper \"AFn.java\" 165]\n  [clojure.lang.RestFn applyTo \"RestFn.java\" 132]\n  [clojure.core$apply invokeStatic \"core.clj\" 650]\n  [clojure.core$apply invoke \"core.clj\" 641]\n  [manifold.deferred$fn__2050$chain___2071$fn__2073 invoke \"deferred.clj\" 889]\n  [manifold.deferred.Listener onSuccess \"deferred.clj\" 219]\n  [manifold.deferred.Deferred$fn__1859 invoke \"deferred.clj\" 379]\n  [clojure.lang.AFn run \"AFn.java\" 22]\n  [io.aleph.dirigiste.Executor$Worker$1 run \"Executor.java\" 62]\n  [manifold.executor$thread_factory$reify__1384$f__1385 invoke \"executor.clj\" 36]\n  [clojure.lang.AFn run \"AFn.java\" 22]\n  [java.lang.Thread run nil -1]]}}"
  }
}`

**Comment by Frozenlock** [comment]
We are about to release a new version. Could you try it and see if you still get these errors?
Here's the ~~[temporary location](#)~~ for the compiled version.

**Comment by senamaud** [comment]
Hi! Thanks for the quick reply.
I have different errors, you can compare them.
My colleague told me that some of the devices may have the wrong date and time. Could it be the source of the problem?

[a-wacnet202-devices10objects.txt](https://github.com/Frozenlock/wacnet/files/433170/a-wacnet202-devices10objects.txt)
[a-wacnet203-devices10objects.txt](https://github.com/Frozenlock/wacnet/files/433174/a-wacnet203-devices10objects.txt)
[b-wacnet202-devices10objects25.txt](https://github.com/Frozenlock/wacnet/files/433173/b-wacnet202-devices10objects25.txt)
[b-wacnet203-devices10objects25.txt](https://github.com/Frozenlock/wacnet/files/433169/b-wacnet203-devices10objects25.txt)
[c-wacnet202-devices10objectsproperties.txt](https://github.com/Frozenlock/wacnet/files/433172/c-wacnet202-devices10objectsproperties.txt)
[c-wacnet203-devices10objectsproperties.txt](https://github.com/Frozenlock/wacnet/files/433171/c-wacnet203-devices10objectsproperties.txt)

**Comment by Frozenlock** [comment]
Ok, I think I found the problem.

Could you tell me if ~~[this version](#)~~ works as expected?

**Comment by senamaud** [comment]
Great! Thanks a lot!
I tested it with the device 10 and it works normally. I will test it over all the devices in few minutes.
I did some other tests of "impossible cases" and I got an error 500 with objects 1 to 30 (these objects doesn't exists) but from 31 and up, there is no error even if the objects also doesn't exists.
Objects 2.30 and 2.31 are ok

I don't know everything about that building so I may be wrong about my assumption.
Anyway, that's not a problem for me as this case should not happen as everything will be automated.

Here is the detail
[wacnet203-alpha9.txt](https://github.com/Frozenlock/wacnet/files/434035/wacnet203-alpha9.txt)

Really good job! Seriously, this will become the core of Bacnet for sure!

**Comment by Frozenlock** [comment]
Thanks to you for letting me know about this! :wink:

**Comment by senamaud** [comment]
I'm finding other errors, how do you want me to send them to you? Here or elsewhere?
I'm welling to help you test it on that building as long as you want.

**Comment by Frozenlock** [comment]
Here is fine.

**Comment by senamaud** [comment]
device 4177, the 10 first are OK, then at 11, got this

http://localhost:47800/api/v1/bacnet/devices/4177/objects?properties=present-value&properties=description&limit=11&page=1

`{
    "status": 500,
    "message": "Internal Server Error",
    "id": "05e68d49-9695-4814-a766-cc5a5fd5984c",
    "error": {
        "error": "clojure.lang.ExceptionInfo: Error on GET {:response #yada.context.Response{:headers {}, :vary #{:media-type}, :produces {:media-type #yada.media_type.MediaTypeMap{:name \"application/json\", :type \"application\", :subtype \"json\", :parameters {}, :quality 1.0}, :charset #yada.charset.CharsetMap{:alias \"UTF-8\", :quality 1.0}}}, :resource yada.resource.Resource, :error #error {\n :cause nil\n :via\n [{:type com.serotonin.bacnet4j.exception.BACnetTimeoutException\n   :message nil\n   :at [com.serotonin.bacnet4j.transport.DefaultTransport expire \"DefaultTransport.java\" 820]}]\n :trace\n [[com.serotonin.bacnet4j.transport.DefaultTransport expire \"DefaultTransport.java\" 820]\n  [com.serotonin.bacnet4j.transport.DefaultTransport run \"DefaultTransport.java\" 422]\n  [java.lang.Thread run nil -1]]}}",
        "data": "{:response #yada.context.Response{:headers {}, :vary #{:media-type}, :produces {:media-type #yada.media_type.MediaTypeMap{:name \"application/json\", :type \"application\", :subtype \"json\", :parameters {}, :quality 1.0}, :charset #yada.charset.CharsetMap{:alias \"UTF-8\", :quality 1.0}}}, :resource yada.resource.Resource, :error #error {\n :cause nil\n :via\n [{:type com.serotonin.bacnet4j.exception.BACnetTimeoutException\n   :message nil\n   :at [com.serotonin.bacnet4j.transport.DefaultTransport expire \"DefaultTransport.java\" 820]}]\n :trace\n [[com.serotonin.bacnet4j.transport.DefaultTransport expire \"DefaultTransport.java\" 820]\n  [com.serotonin.bacnet4j.transport.DefaultTransport run \"DefaultTransport.java\" 422]\n  [java.lang.Thread run nil -1]]}}"
    }
}`

**Comment by Frozenlock** [comment]
> com.serotonin.bacnet4j.exception.BACnetTimeoutException

That looks like a normal timeout.
You could try to go in the `config` tab and increase the delay between timeouts.

**Comment by senamaud** [comment]
went from 6000 to 24000 and same result
is there a way I could get the list of objects of a device?
This way, I could identify the culprit.

I also get the timeout when I ask for this
http://localhost:47800/api/v1/bacnet/devices/4177/objects

**Comment by Frozenlock** [comment]
Well, the last address you gave should be the one giving you the list of objects.
If you could give me a shell or vpn access, I'd be able to connect and check out what's happening. frozenlock@gmail.com

Edit: or even forward the port 47999, which would allow me to connect directly in Wacnet.

**Comment by senamaud** [comment]
in the console, I see this

Couldn't retrieve array length : {:error {:error-class :property, :error-code :u
nknown-property}}
Error for :  ([:device 4177] :object-list) :segmentation-not-supported
Trying to read as an array (in chunks).

**Comment by Frozenlock** [comment]
The first error is telling you that you tried to retrieve a property that is unknown to the target device.

The second is because the object-list is too big to fit into a single packet, so we try to read it in parts. (Which should succeed.)

In the `repl` tab, enter the following and press enter:

``` clj
(bacure.core/remote-object-properties nil 4177 [:device 4177] :object-list)
```

It should return the list of objects for the device 4177.

**Comment by senamaud** [comment]
Give me some Clojure:

> (bacure.core/remote-object-properties nil 4177 [:device 4177] :object-list)
> com.serotonin.bacnet4j.exception.BACnetTimeoutException

**Comment by senamaud** [comment]
I sent you an e-mail :)

**Comment by Frozenlock** [comment]
Looks fixed. Let me know if it occurs again.
