### ISSUE TITLE
error type com.serotonin.bacnet4j.exception.BACnetTimeoutException

### ISSUE THREAD

**Issue by senamaud** [Frozenlock/wacnet#4]
Hi!
I used the newest version (2.1.0) and executed it this API command on all 362 devices detected

curl "http://localhost:47800/api/v1/bacnet/devices/4177/objects?limit=1000&page=1&properties=present-value&properties=description"

Where here 4177 is the device ID. I got only 5 devices having the same issue of timeout. 
They have exactly the same error (except, of course, for the ID). After you tested it on my server, I pressed the "refresh" button (WhoIs) and I got again the timeout on 4177 again.

On our side, we are looking on these devices trying to detect what problem they could have.

`{"status":500,"message":"Internal Server Error","id":"892f9abb-c42d-45cf-a06b-792b96d49d3c","error":{"error":"clojure.lang.ExceptionInfo: Error on GET {:response #yada.context.Response{:headers {}, :vary #{:media-type}, :produces {:media-type #yada.media_type.MediaTypeMap{:name \"application/json\", :type \"application\", :subtype \"json\", :parameters {}, :quality 1.0}, :charset #yada.charset.CharsetMap{:alias \"UTF-8\", :quality 1.0}}}, :resource yada.resource.Resource, :error #error {\n :cause nil\n :via\n [{:type com.serotonin.bacnet4j.exception.BACnetTimeoutException\n   :message nil\n   :at [com.serotonin.bacnet4j.transport.DefaultTransport expire \"DefaultTransport.java\" 820]}]\n :trace\n [[com.serotonin.bacnet4j.transport.DefaultTransport expire \"DefaultTransport.java\" 820]\n  [com.serotonin.bacnet4j.transport.DefaultTransport run \"DefaultTransport.java\" 422]\n  [java.lang.Thread run nil -1]]}}","data":"{:response #yada.context.Response{:headers {}, :vary #{:media-type}, :produces {:media-type #yada.media_type.MediaTypeMap{:name \"application/json\", :type \"application\", :subtype \"json\", :parameters {}, :quality 1.0}, :charset #yada.charset.CharsetMap{:alias \"UTF-8\", :quality 1.0}}}, :resource yada.resource.Resource, :error #error {\n :cause nil\n :via\n [{:type com.serotonin.bacnet4j.exception.BACnetTimeoutException\n   :message nil\n   :at [com.serotonin.bacnet4j.transport.DefaultTransport expire \"DefaultTransport.java\" 820]}]\n :trace\n [[com.serotonin.bacnet4j.transport.DefaultTransport expire \"DefaultTransport.java\" 820]\n  [com.serotonin.bacnet4j.transport.DefaultTransport run \"DefaultTransport.java\" 422]\n  [java.lang.Thread run nil -1]]}}"}}
`

What are the commands you executed in REPL console?

**Comment by Frozenlock** [comment]
Hello,

Nothing in particular... I was manually asking for the same information the
API or the user interface is asking for.

(Objects list, present-values, etc...)

I did reboot Wacnet's local BACnet device (in the config tab), but it
shouldn't do much...

I could connect on your PC like last time and check with wireshark what
your devices are really doing.
(Is it really a timeout, or are they sending some incomprehensible message?)
This weekend or early next week I should have some time.

**Comment by Frozenlock** [comment]
@senamaud, are you available in the next few days to give me an access to your network?

**Comment by Frozenlock** [comment]
I'm gonna close this. Please re-open if you can prove it's a Wacnet problem and not the other device's fault.
